In [ ]:
import numpy as np
import pandas as pd

In [ ]:
Data=pd.read_csv('car.csv')
Data.head()

Buying Maintenance Doors Persons Lugboot Safety  Class
0  vhigh       vhigh     2       2   small    med  unacc
1  vhigh       vhigh     2       2   small   high  unacc
2  vhigh       vhigh     2       2     med    low  unacc
3  vhigh       vhigh     2       2     med    med  unacc
4  vhigh       vhigh     2       2     med   high  unacc

In [ ]:
#Data.isnull().sum()
df=pd.DataFrame(Data)
df.head()

Buying Maintenance Doors Persons Lugboot Safety  Class
0  vhigh       vhigh     2       2   small    med  unacc
1  vhigh       vhigh     2       2   small   high  unacc
2  vhigh       vhigh     2       2     med    low  unacc
3  vhigh       vhigh     2       2     med    med  unacc
4  vhigh       vhigh     2       2     med   high  unacc

In [ ]:
new_row = pd.DataFrame({'Buying':'vhigh', 'Maintenance':'vhigh', 'Doors':2,
                        'Persons':'2', 'Lugboot':'small', 'Safety':'low',
                        'Class':'unacc'},index =[0])

In [ ]:
df=pd.DataFrame(Data)
df

Buying Maintenance  Doors Persons Lugboot Safety  Class
0     vhigh       vhigh      2       2   small    med  unacc
1     vhigh       vhigh      2       2   small   high  unacc
2     vhigh       vhigh      2       2     med    low  unacc
3     vhigh       vhigh      2       2     med    med  unacc
4     vhigh       vhigh      2       2     med   high  unacc
...     ...         ...    ...     ...     ...    ...    ...
1722    low         low  5more    more     med    med   good
1723    low         low  5more    more     med   high  vgood
1724    low         low  5more    more     big    low  unacc
1725    low         low  5more    more     big    med   good
1726    low         low  5more    more     big   high  vgood

[1727 rows x 7 columns]

In [ ]:
df = pd.concat([new_row, df]).reset_index(drop = True)
df.head(5)

Buying Maintenance Doors Persons Lugboot Safety  Class
0  vhigh       vhigh     2       2   small    low  unacc
1  vhigh       vhigh     2       2   small    med  unacc
2  vhigh       vhigh     2       2   small   high  unacc
3  vhigh       vhigh     2       2     med    low  unacc
4  vhigh       vhigh     2       2     med    med  unacc

In [ ]:
from sklearn.preprocessing import LabelEncoder
Buy=LabelEncoder()
Maint=LabelEncoder()

Lugboo=LabelEncoder()
Safe=LabelEncoder()
classs=LabelEncoder()
df['Buying']=Buy.fit_transform(df['Buying'])
df['Maintenance']=Maint.fit_transform(df['Maintenance'])
df['Lugboot']=Lugboo.fit_transform(df['Lugboot'])
df['Safety']=Safe.fit_transform(df['Safety'])
df['Class']=classs.fit_transform(df['Class'])

In [ ]:
df['Doors'],Doooor=pd.factorize(df['Doors'])
df['Persons'],perss=pd.factorize(df['Persons'])

In [ ]:
df

Buying  Maintenance  Doors  Persons  Lugboot  Safety  Class
0          3            3      0        0        2       1      2
1          3            3      1        0        2       2      2
2          3            3      1        0        2       0      2
3          3            3      1        0        1       1      2
4          3            3      1        0        1       2      2
...      ...          ...    ...      ...      ...     ...    ...
1723       1            1      4        2        1       2      1
1724       1            1      4        2        1       0      3
1725       1            1      4        2        0       1      2
1726       1            1      4        2        0       2      1
1727       1            1      4        2        0       0      3

[1728 rows x 7 columns]

In [ ]:
X=df.drop(['Class'],axis=1)
Y=df['Class']

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=1)

In [ ]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
model.fit(X_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [ ]:
model.score(X_test,y_test)

0.6791907514450867

In [ ]:
y_pred = model.predict(X_test)
y_pred

array([2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 0, 2, 3, 2, 2, 3,
       2, 2, 2, 3, 3, 2, 2, 0, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2,
       3, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 3, 2, 3, 3, 2,
       2, 3, 3, 2, 2, 2, 2, 2, 0, 2, 2, 3, 3, 0, 2, 2, 3, 2, 2, 3, 3, 3,
       3, 2, 3, 2, 2, 2, 2, 3, 2, 3, 2, 2, 3, 2, 2, 2, 2, 2, 3, 2, 2, 3,
       2, 2, 2, 2, 3, 2, 2, 0, 3, 2, 2, 2, 3, 3, 3, 2, 2, 2, 3, 2, 2, 2,
       2, 3, 3, 2, 3, 3, 3, 2, 2, 2, 2, 2, 2, 3, 2, 3, 2, 2, 2, 2, 2, 2,
       2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 3,
       3, 2, 2, 2, 2, 2, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 3, 2, 2,
       2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 3, 2, 3, 2, 3, 3, 2, 2, 0, 2, 2, 2,
       2, 0, 2, 2, 2, 2, 3, 2, 3, 3, 2, 2, 2, 2, 0, 2, 3, 2, 2, 2, 2, 3,
       2, 2, 2, 3, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 3, 2, 3, 2, 2, 2, 3,
       2, 2, 3, 2, 0, 2, 2, 2, 2, 2, 2, 3, 2, 3, 3,

In [ ]:
model.predict_proba(X_test)

array([[3.32312228e-01, 8.31182797e-02, 5.84569492e-01, 0.00000000e+00],
       [5.26748622e-01, 9.64128920e-04, 4.72287249e-01, 0.00000000e+00],
       [1.44643634e-02, 2.89325659e-05, 9.85506704e-01, 0.00000000e+00],
       ...,
       [1.88488722e-03, 1.49184328e-06, 9.14498371e-02, 9.06663784e-01],
       [3.53766591e-01, 7.69793169e-06, 6.46225711e-01, 0.00000000e+00],
       [2.16480799e-01, 4.59546502e-06, 7.83514605e-01, 0.00000000e+00]])

In [ ]:
from sklearn.metrics import accuracy_score
print("Our accuracy is:", accuracy_score(y_pred, y_test)*100, "%")

Our accuracy is: 67.91907514450867 %


In [ ]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[  7,   0,  29,  23],
       [  3,   0,   5,   6],
       [  4,   0, 215,  41],
       [  0,   0,   0,  13]])