In [1]:
import pandas as pd
import numpy as np

In [3]:
Data=pd.read_csv('covid.csv')
Data.head()

s.no  AGE  TEMPERATURE   BP  OXYGEN COVID
0     0   58          103  170      80   Yes
1     1   25          100  165      90   Yes
2     2   18           98  120      94    No
3     3   61          102  180      91   Yes
4     4   21           99  140      95    No

In [4]:
df=pd.DataFrame(Data)
df.head()

s.no  AGE  TEMPERATURE   BP  OXYGEN COVID
0     0   58          103  170      80   Yes
1     1   25          100  165      90   Yes
2     2   18           98  120      94    No
3     3   61          102  180      91   Yes
4     4   21           99  140      95    No

In [5]:
from sklearn.preprocessing import LabelEncoder
covid=LabelEncoder()
df['covid']=covid.fit_transform(df['COVID'])
df.drop(['COVID'],axis=1,inplace=True)
df.head()

s.no  AGE  TEMPERATURE   BP  OXYGEN  covid
0     0   58          103  170      80      1
1     1   25          100  165      90      1
2     2   18           98  120      94      0
3     3   61          102  180      91      1
4     4   21           99  140      95      0

In [9]:
X=df.drop(['s.no','covid'],axis=1)
y=df['covid']
#print(X)
#print(y)

In [19]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

In [20]:
from sklearn.preprocessing import StandardScaler    
st_x= StandardScaler()    
X_train= st_x.fit_transform(X_train)    
X_test= st_x.transform(X_test)

In [21]:
print(X_train)
print(X_test)

[[-1.2548526  -0.74535599 -1.99309288  0.71509694]
 [-0.37204173  0.          0.53336288 -0.23836565]
 [ 1.33052211  0.372678   -0.30878904  0.71509694]
 [-0.81344716  0.          0.53336288 -0.23836565]
 [-0.68733133  0.         -0.87022365  0.71509694]
 [ 0.44771123  0.372678    0.25264558  0.        ]
 [ 1.45663795  0.74535599  1.3755148   0.        ]
 [ 1.26746419  1.11803399  0.81408019 -2.62202212]
 [-1.19179468 -2.60874597 -1.15094096  1.19182824]
 [-0.18286797  0.74535599  0.81408019 -0.23836565]]
[[ 2.08721714  1.11803399  0.81408019  0.        ]
 [ 1.70886963  0.74535599  0.87022365 -0.47673129]
 [-1.06567884 -0.372678   -0.87022365  0.95346259]
 [-0.30898381 -1.11803399 -0.87022365  0.71509694]]


In [22]:
from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier(n_neighbors=3)
model.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [23]:
y_pred=model.predict(X_test)
y_pred

array([1, 1, 0, 0])

In [24]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      1.00      1.00         2

    accuracy                           1.00         4
   macro avg       1.00      1.00      1.00         4
weighted avg       1.00      1.00      1.00         4

[[2 0]
 [0 2]]
